### ISSUE TITLE
Any plan for hook over network protocols such as websocket?

### ISSUE THREAD

**Issue by tigerinus** [mikestefanello/hooks#2]
This lib looks great and promising. However my project includes multiple services running in separate processes, or even separate devices in future. Would love to see this lib to have network support.

Cheers.

**Comment by mikestefanello** [comment]
Thanks! I'm glad to hear that. If you haven't yet seen, I recently published a [full-app example](https://github.com/mikestefanello/hooks-example) using hooks and [do](https://github.com/samber/do) that I think has some interesting patterns and use-cases. You may find it useful.

Regarding network support, I assumed anyone needing that would opt for something like a message queue. Are you able to share how you would want to use hooks over the network? I'm especially curious if you'd want bi-directional communication rather than just broadcasting messages.

**Comment by tigerinus** [comment]
>  Are you able to share how you would want to use hooks over the network?

Yeah, my project is meant to run on devices with limited CPU and memory resources. Currently there are 3 microservice-like processes which needs a hook-like mechanism to communicate between each other. So running a message queue like RabbitMQ or Kafka isn't really practical. I've been looking for a tiny lightweight alternative (about to give up and write my own).

Because for now the processes don't run on more than one device, so CAP theorem doesn't really apply, which makes implementing such an alternative easier I suppose.

**Comment by mikestefanello** [comment]
Do you need bi-directional communication (ie, either getting a response from a listener or allowing it to alter the data in the message)? What about things like automatic retries in the event of a communication failure?

It's an interesting idea, but I don't think it's something that I would pursue for this project, given the complexity it introduces, and because outside of your unique situation, I can't imagine many others would find this a useful addition.

**Comment by tigerinus** [comment]
Bi-directional communication is no needed.

Fair enough. Even without hook over network this is still a great package I'd consider make my project to depend on.  Keep it up!

**Comment by mikestefanello** [comment]
Thanks again. If you do find something that fits your needs, or you end up building one yourself, let me know.
